//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orc.Snapshots.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orc.Snapshots.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string Snapshots_AreYouSure {
            get {
                return ResourceManager.GetString("Snapshots_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove snapshot &apos;{0}&apos;?.
        /// </summary>
        internal static string Snapshots_AreYouSureYouWantToRemoveTheSnapshot {
            get {
                return ResourceManager.GetString("Snapshots_AreYouSureYouWantToRemoveTheSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum age of a snapshot in days:.
        /// </summary>
        internal static string Snapshots_CleanupMaxAge {
            get {
                return ResourceManager.GetString("Snapshots_CleanupMaxAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current number of items selected for cleanup:.
        /// </summary>
        internal static string Snapshots_CleanupSummary {
            get {
                return ResourceManager.GetString("Snapshots_CleanupSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean up snapshots.
        /// </summary>
        internal static string Snapshots_CleanupTitle {
            get {
                return ResourceManager.GetString("Snapshots_CleanupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new snapshot.
        /// </summary>
        internal static string Snapshots_CreateNewSnapshot {
            get {
                return ResourceManager.GetString("Snapshots_CreateNewSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Snapshots_Edit {
            get {
                return ResourceManager.GetString("Snapshots_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit snapshot {0}.
        /// </summary>
        internal static string Snapshots_EditSnapshot {
            get {
                return ResourceManager.GetString("Snapshots_EditSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No snapshots available.
        /// </summary>
        internal static string Snapshots_NoSnapshots {
            get {
                return ResourceManager.GetString("Snapshots_NoSnapshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Snapshots_Remove {
            get {
                return ResourceManager.GetString("Snapshots_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string Snapshots_Restore {
            get {
                return ResourceManager.GetString("Snapshots_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot.
        /// </summary>
        internal static string Snapshots_Snapshot {
            get {
                return ResourceManager.GetString("Snapshots_Snapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot with current title already exists.
        /// </summary>
        internal static string Snapshots_SnapshotWithCurrentTitleAlreadyExists {
            get {
                return ResourceManager.GetString("Snapshots_SnapshotWithCurrentTitleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Snapshots_Title {
            get {
                return ResourceManager.GetString("Snapshots_Title", resourceCulture);
            }
        }
    }
}
